# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# soil.py
# Created on: 2017-02-12 21:39:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
soils = "soils"
basin = "basin"
soil_clip_shp = "C:\\Users\\lxi1\\Desktop\\GEOG 503\\lab\\lab 3\\data\\data\\Results\\soil_clip.shp"
not_farmland_shp = "C:\\Users\\lxi1\\Desktop\\GEOG 503\\lab\\lab 3\\data\\data\\Results\\not_farmland.shp"

# Process: Clip
arcpy.Clip_analysis(soils, basin, soil_clip_shp, "")

# Process: Select
arcpy.Select_analysis(soil_clip_shp, not_farmland_shp, "\"FARMLNDCL\" = 'Not prime farmland'")

